***
--------------------------------------------------
TIME OF OCCURENCE:---
30-05-2025 06:48:13

ERROR DETAILS:---
Type:
NameError

Error Message:
name 'generate_password_hash' is not defined

Origin:
C:\Projects\Learning\Eenovate\eGauge\website\auth.py

Line:
224
---
--------------------------------------------------

***
--------------------------------------------------
TIME OF OCCURENCE:---
30-05-2025 06:48:48

ERROR DETAILS:---
Type:
NameError

Error Message:
name 'generate_password_hash' is not defined

Origin:
C:\Projects\Learning\Eenovate\eGauge\website\auth.py

Line:
224
---
--------------------------------------------------

***
--------------------------------------------------
TIME OF OCCURENCE:---
30-05-2025 06:50:32

ERROR DETAILS:---
Type:
DataError

Error Message:
1264 (22003): Out of range value for column 'phone' at row 1

Origin:
C:\Projects\Learning\Eenovate\eGauge\.venv\Lib\site-packages\mysql\connector\connection_cext.py

Line:
781
---
--------------------------------------------------

***
--------------------------------------------------
TIME OF OCCURENCE:---
30-05-2025 06:51:34

ERROR DETAILS:---
Type:
BuildError

Error Message:
Could not build url for endpoint 'auth.login'. Did you mean 'auth.logout' instead?

Origin:
C:\Projects\Learning\Eenovate\eGauge\.venv\Lib\site-packages\werkzeug\routing\map.py

Line:
924
---
--------------------------------------------------

